# language: generic
# Only need this if build fails with rakefile not found
sudo: required
# gives travis superuser level
services:
  - docker # Travis CI will automatically install Docker into our running container

# some series of steps before deployment/testing
before_install:
  - docker build -t nbharucha/docker-react -f Dockerfile.dev .

# looks at status code/result of npm run test
# instead of -- --coverage
# use -e CI=true, CI will make it run once.
script:
  - docker run -e CI=true nbharucha/docker-react npm run test

# tells travis ci how to deploy our app
# Set Environment Variables within travis-ci.org -> settings -> Environment Variables
deploy:
  provider: elasticbeanstalk
  region: "us-east-2" # Ohio
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-258063334742" # beanstalk generates S3 bucket for you
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
